name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    steps:
      - name: Deploy React
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd projects/mcrm/static/avto-zapchasti.uz
            git pull  
