name: Deploy
on: [push,workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          npm ci
          npm run build
      - uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.DEMO_AVTOZAPCHASTI_USER }}
          password: ${{ secrets.DEMO_AVTOZAPCHASTI_PASSWORD }}
          local-dir: ./out/